### ISSUE TITLE
Using p910nd instead of LPR in the printer.service

### ISSUE THREAD

**Issue by MegaZeroX10** [troglobit/mdnsd#26]
How do I do that? Is it as simple as changing the port in that file to 9100?

**Comment by troglobit** [comment]
I do not know what a p910nd is.  You can try, but maybe you need a separate service announcement, like _pdl_datastream._tcp, or similar.  I dunno what your clients need.  

I would suggest reading up on https://developer.apple.com/bonjour/printing-specification/bonjourprinting-1.2.1.pdf or maybe changing to an mDNS daemon supported by your operating system. (GitHub is not a support page for end-users).

**Comment by MegaZeroX10** [comment]
1. https://github.com/kenyapcomau/p910nd
2. Then what would be a support page for it?

**Comment by troglobit** [comment]
Since there is nobody paying me currently to work on this project, I have no means to provide support for end-users without it affecting other (paying) projects or my precious little spare time.  I suggest you instead try out another mDNS daemon supported by your operating system/distribution/firmware.

**Comment by MegaZeroX10** [comment]
How about adding a Sponsor button to this repository?
