### ISSUE TITLE
combine with my version of mdnsd

### ISSUE THREAD

**Issue by cooljeanius** [troglobit/mdnsd#45]
I also have my own fork of mdnsd here: https://github.com/cooljeanius/mdnsd 
When suggesting the MacPorts port be updated, it was suggested that we combine our versions so as to reduce duplication of efforts. Should I try submitting a pull request, or can you think of another way to get them merged?

**Comment by troglobit** [comment]
That's a difficult question to answer. When I began my restoration effort back in 2016, I could not find any other forks.  I have made lots of changes to the code base since, and tried to manually merge in relevant changes from forks from my version that have surfaced.  

Since you know best what changes you've made, and I'm pressed for time atm. due to other high-prio projects, I suggest a pull request for each relevant change.

I'd like to get a release out of mdnsd soonish, only showstopper for me is to add per-interface support.

**Comment by cooljeanius** [comment]
On further thought, they've probably diverged too much for this to be easy enough for me to figure out; closing...
